import cv2
import torch
import numpy as np
import base64
import json
import os
from pathlib import Path
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, File, UploadFile
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import requests
from ultralytics import YOLO

import fuzzy_engine
from segment_anything import sam_model_registry, SamPredictor
from fastapi.middleware.cors import CORSMiddleware

BASE_DIR = Path(__file__).resolve().parent

app = FastAPI()

# --- CRITICAL FIX: Add CORS Middleware ---
# This allows your Next.js frontend to actually get the data back
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows Next.js to talk to Python
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

load_dotenv(BASE_DIR / ".env")

# --- Local LLM (decision D2) -------------------------------------------------
# The bulletin is generated by a local Ollama model. Nothing leaves this machine,
# which is what the paper's RA 10173 compliance claim (section 3.5) depends on.
OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.2")

# --- Ground Sample Distance (decision D3) ------------------------------------
# mm per pixel in the bird's-eye view. Default is the value stated in the paper,
# section 3.3.C. Callers may override it per image once capture height and
# distance are known. The previous hardcoded 1.5 understated every measurement
# by a factor of ~2.9 (and every area by ~8.4).
DEFAULT_GSD_MM_PX = float(os.environ.get("DEFAULT_GSD_MM_PX", "4.357"))

# --- Road gate ----------------------------------------------------------------
# Minimum share of the frame that ultrabestroad.pt must segment as road surface
# before the image is accepted for analysis.
#
# Without this, any photograph at all produced a confident-looking assessment:
# the crack detector will happily find "cracks" in a wall, a carpet or a face,
# and the symbolic layer then grades them in millimetres and recommends DPWH
# interventions. An assessment tool that answers questions about non-roads is
# worse than one that refuses, because the output looks authoritative either way.
#
# 15% is deliberately permissive -- a legitimate close-up of a defect taken at
# 2 m still fills most of the frame with pavement, while a photo of something
# else rarely reaches it.
MIN_ROAD_COVERAGE = float(os.environ.get("MIN_ROAD_COVERAGE", "0.15"))

print("Loading AI models into memory. This may take a moment...")


def _require(path: Path, what: str, how: str) -> Path:
    """Model weights are required. Fail at startup, not on the first request."""
    if not path.exists():
        raise RuntimeError(f"{what} not found at {path}" + chr(10) + f"  -> {how}")
    return path


# Paths resolve against this file, so the server runs from any working directory.
ROAD_WEIGHTS = _require(
    BASE_DIR / "ultrabestroad.pt",
    "Road segmentation weights",
    "Restore ultrabestroad.pt into backend/ (see Setup & Run note).",
)
CRACK_WEIGHTS = _require(
    BASE_DIR / "best.pt",
    "Crack detection weights",
    "Restore best.pt into backend/ (see Setup & Run note).",
)
SAM_CHECKPOINT = _require(
    BASE_DIR / "sam_files" / "sam_vit_b_01ec64.pth",
    "SAM checkpoint",
    "Download sam_vit_b_01ec64.pth into backend/sam_files/ "
    "from https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth",
)

road_model = YOLO(str(ROAD_WEIGHTS))
crack_model = YOLO(str(CRACK_WEIGHTS))

# Privacy preprocessing (paper section 3.3.D: "automated blurring for data
# privacy"). Uses stock COCO YOLOv8n to find people and vehicles. Ultralytics
# fetches the 6 MB weights on first use.
#
# Disabling this weakens the RA 10173 position in section 3.5, so it is opt-out
# rather than opt-in, and a failure to load is fatal rather than silently
# skipped: a privacy control that quietly does nothing is worse than none.
PRIVACY_BLUR_ENABLED = os.environ.get("PRIVACY_BLUR_ENABLED", "true").lower() != "false"
privacy_model = None
if PRIVACY_BLUR_ENABLED:
    try:
        privacy_model = YOLO(str(BASE_DIR / "yolov8n.pt"))
    except Exception as exc:
        raise RuntimeError(
            "Privacy blur is enabled but yolov8n.pt could not be loaded "
            f"({exc}). Place it in backend/, or set PRIVACY_BLUR_ENABLED=false "
            "to run without blurring (documented as a privacy regression)."
        ) from exc

sam = sam_model_registry["vit_b"](checkpoint=str(SAM_CHECKPOINT))
predictor = SamPredictor(sam)

print(f"Models loaded. Bulletin model: {OLLAMA_MODEL} at {OLLAMA_HOST}. Server is ready.")

# ==========================================
# 2. DATA MODELS & UTILS
# ==========================================
class ImageRequest(BaseModel):
    image_base64: str
    # Optional per-image override once capture height/distance are known (D3).
    gsd_mm_px: float | None = None

SEVERITY_RANK = {"Low": 0, "Medium": 1, "High": 2}


def worst_severity(distresses):
    """Overall severity is the WORST distress found, never just the first one.

    The previous version returned traced_data[0]['severity'], so an image whose
    first detection was a hairline crack reported "Low" even when it also
    contained a high-severity pothole. For a maintenance prioritisation tool
    that is the one direction the error must never go.
    """
    if not distresses:
        return "Low"
    return max(
        (d.get("severity", "Low") for d in distresses),
        key=lambda sev: SEVERITY_RANK.get(sev, 0),
    )


# COCO class ids. People are blurred whole; vehicles only where plates sit.
PRIVACY_PERSON_CLASS = 0
PRIVACY_VEHICLE_CLASSES = {1, 2, 3, 5, 7}  # bicycle, car, motorcycle, bus, truck

# Plates sit low on a vehicle. Blurring the whole vehicle would often cover the
# road defect behind it, so only the bottom band is obscured.
PRIVACY_PLATE_BAND = 0.45


def _blur_region(img, x1, y1, x2, y2):
    x1, y1 = max(0, x1), max(0, y1)
    x2, y2 = min(img.shape[1], x2), min(img.shape[0], y2)
    if x2 <= x1 or y2 <= y1:
        return

    roi = img[y1:y2, x1:x2]
    # Kernel scales with region size so small faces are as unrecoverable as large ones.
    k = max(9, (min(roi.shape[:2]) // 4) | 1)
    img[y1:y2, x1:x2] = cv2.GaussianBlur(roi, (k, k), 0)


def apply_privacy_blur(img):
    """Obscure people and vehicle plates before any detection or storage.

    Runs on the raw upload, so no identifiable frame is ever measured, encoded
    into the returned annotated image, or written to the database.
    """
    if not PRIVACY_BLUR_ENABLED or privacy_model is None:
        return img

    try:
        results = privacy_model.predict(img, conf=0.35, verbose=False)
    except Exception as exc:
        print(f"Privacy blur failed: {exc}")
        return img

    if not results or results[0].boxes is None:
        return img

    boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
    classes = results[0].boxes.cls.cpu().numpy().astype(int)

    blurred = 0
    for (x1, y1, x2, y2), cls in zip(boxes, classes):
        if cls == PRIVACY_PERSON_CLASS:
            _blur_region(img, x1, y1, x2, y2)
            blurred += 1
        elif cls in PRIVACY_VEHICLE_CLASSES:
            band_top = int(y2 - (y2 - y1) * PRIVACY_PLATE_BAND)
            _blur_region(img, x1, band_top, x2, y2)
            blurred += 1

    if blurred:
        print(f"Privacy blur applied to {blurred} region(s).")
    return img


def road_mask_area_px(road_results, image_shape):
    """Road surface area in pixels, used as the density denominator when IPM fails."""
    if road_results[0].masks is None:
        return 0

    h, w = image_shape[:2]
    masks = road_results[0].masks.data.cpu().numpy()
    combined = np.zeros((masks.shape[1], masks.shape[2]), dtype=np.uint8)
    for m in masks:
        combined = np.maximum(combined, m)

    resized = cv2.resize((combined * 255).astype(np.uint8), (w, h))
    return int(cv2.countNonZero(resized))


def decode_base64_img(base64_str):
    """Converts a Base64 string from Next.js into a standard OpenCV image array."""
    try:
        header, encoded = base64_str.split(",", 1) if "," in base64_str else ("", base64_str)
        img_bytes = base64.b64decode(encoded)
        np_arr = np.frombuffer(img_bytes, np.uint8)
        return cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
    except Exception as e:
        print(f"Error decoding image: {e}")
        return None


def detect_road(model, img):
    road_results = road_model.predict(img)
    return road_results

def get_birds_eye_view(img, road_results):
    """Warp the road surface to a top-down 700x700 view.

    Returns (image, ipm_applied). The flag matters for crack density: when the
    warp succeeds the whole frame is road surface, so the denominator is the
    frame. When it fails we fall back to the original image, where most of the
    frame is sky, buildings and verge, and using it as the denominator would
    understate density badly.
    """
    h, w = img.shape[:2]

    if road_results[0].masks is None:
        return img.copy(), False

    # Extract and resize the road mask
    masks = road_results[0].masks.data.cpu().numpy()
    combined = np.zeros((masks.shape[1], masks.shape[2]), dtype=np.uint8)
    for m in masks:
        combined = np.maximum(combined, m)
    
    mask = (combined * 255).astype(np.uint8)
    mask = cv2.resize(mask, (w, h))

    # Clean mask noise
    kernel = np.ones((5,5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    # Scan road edges at specific horizontal lines
    ys = np.linspace(int(h*0.3), int(h*0.95), 60).astype(int)
    left_edges, right_edges, valid_ys = [], [], []

    for y in ys:
        xs = np.where(mask[y] > 0)[0]
        if len(xs) > 0 and (xs.max() - xs.min()) > w * 0.1:
            left_edges.append(xs.min())
            right_edges.append(xs.max())
            valid_ys.append(y)

    if len(left_edges) < 10:
        return img.copy(), False

    # Smooth edges with polynomial fitting
    le = np.polyval(np.polyfit(range(len(left_edges)), left_edges, 2), range(len(left_edges))).astype(int)
    re = np.polyval(np.polyfit(range(len(right_edges)), right_edges, 2), range(len(right_edges))).astype(int)

    # Define trapezoid source points
    top_idx, bot_idx = len(le) // 8, -len(le) // 8
    top_l, top_r = int(np.mean(le[:top_idx])), int(np.mean(re[:top_idx]))
    bot_l, bot_r = int(np.mean(le[bot_idx:])), int(np.mean(re[bot_idx:]))
    top_y, bot_y = valid_ys[0], valid_ys[-1]

    # Expand trapezoid for wider field of view
    expand = int((bot_r - bot_l) * 0.25)
    src = np.float32([
        [max(0, top_l - expand), top_y],
        [min(w-1, top_r + expand), top_y],
        [max(0, bot_l - expand), bot_y],
        [min(w-1, bot_r + expand), bot_y]
    ])

    # Map to rectangular destination points
    width, height = 700, 700
    dst = np.float32([[0, 0], [width, 0], [0, height], [width, height]])

    # Apply perspective transformation
    M = cv2.getPerspectiveTransform(src, dst)
    bev = cv2.warpPerspective(img, M, (width, height))

    return bev, True

def detect_crack(model, bev_img):
    crack_results = crack_model.predict(bev_img, conf=0.1) #confidence 
    return crack_results

def filter_overlapping_boxes(boxes, iou_threshold=0.4):
    """Non-maximum suppression. Returns the INDICES that survive.

    Indices (not a Boxes slice) because the caller must use the same positions
    to look up masks, confidences and class ids. Returning a slice is what let
    the previous version silently fall back to the unfiltered detections.
    """
    if boxes is None or len(boxes) == 0:
        return []

    boxes_xyxy = boxes.xyxy.cpu().numpy()
    scores = boxes.conf.cpu().numpy()

    indices = cv2.dnn.NMSBoxes(
        bboxes=[(int(x1), int(y1), int(x2 - x1), int(y2 - y1)) for x1, y1, x2, y2 in boxes_xyxy],
        scores=scores.tolist(),
        score_threshold=0.0,
        nms_threshold=iou_threshold,
    )

    if len(indices) == 0:
        return []

    return [int(i) for i in np.array(indices).flatten()]


def skeletonize_opencv(img):
    skel = np.zeros(img.shape, np.uint8)
    element = cv2.getStructuringElement(cv2.MORPH_CROSS, (3,3))

    while True:
        open_ = cv2.morphologyEx(img, cv2.MORPH_OPEN, element)
        temp = cv2.subtract(img, open_)
        eroded = cv2.erode(img, element)
        skel = cv2.bitwise_or(skel, temp)
        img = eroded.copy()

        if cv2.countNonZero(img) == 0:
            break

    return skel

def trace_cracks(image, crack_results, predictor, gsd, road_area_px):
    """Measure every surviving detection, then grade it.

    Two passes on purpose. Crack density is a property of the whole road segment,
    not of one detection, so no defect can be graded until every defect has been
    measured. The previous single-pass version graded each detection in isolation,
    which is why density -- a stated key feature -- was never computed at all.

    Returns (traced, debug_img, pure_skeleton, density_pct).
    """
    empty = ([], image.copy(), np.zeros(image.shape[:2], dtype=np.uint8), 0.0)

    if not crack_results or crack_results[0].masks is None:
        return empty

    keep_indices = filter_overlapping_boxes(crack_results[0].boxes)
    if len(keep_indices) == 0:
        return empty

    predictor.set_image(image)
    debug_img = image.copy()
    pure_skeleton = np.zeros(image.shape[:2], dtype=np.uint8)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    yolo_masks = crack_results[0].masks.data
    yolo_boxes = crack_results[0].boxes.xyxy.cpu().numpy().astype(int)
    confidences = crack_results[0].boxes.conf.cpu().numpy()
    class_ids = crack_results[0].boxes.cls.cpu().numpy().astype(int)
    names = crack_results[0].names

    # ---- Pass 1: segment, skeletonize, measure -----------------------------
    measured = []
    total_defect_px = 0

    for i in keep_indices:
        x1, y1, x2, y2 = yolo_boxes[i]
        label = names[class_ids[i]]

        masks, _, _ = predictor.predict(box=np.array([x1, y1, x2, y2]), multimask_output=False)
        sam_mask = masks[0].astype(np.uint8) * 255
        y_mask_raw = yolo_masks[i].cpu().numpy()
        y_mask_resized = cv2.resize(y_mask_raw, (image.shape[1], image.shape[0]))
        y_mask_binary = (y_mask_resized > 0.5).astype(np.uint8) * 255
        consensus_mask = cv2.bitwise_and(sam_mask, y_mask_binary)

        roi_fence = consensus_mask[y1:y2, x1:x2]
        roi_gray = gray[y1:y2, x1:x2]
        crack_pixels = cv2.adaptiveThreshold(
            cv2.GaussianBlur(roi_gray, (5, 5), 0), 255,
            cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 15, 5
        )
        valid_cracks = cv2.bitwise_and(crack_pixels, roi_fence)
        cleaned_cracks = cv2.morphologyEx(valid_cracks, cv2.MORPH_OPEN, np.ones((2, 2), np.uint8))

        mask_pixels = cv2.countNonZero(cleaned_cracks)
        if mask_pixels < 10:
            continue

        skel = skeletonize_opencv(cleaned_cracks)
        length_px = cv2.countNonZero(skel)

        # Mean width: mask area divided by centreline length, scaled to mm.
        width_mm = (mask_pixels / length_px * gsd) if length_px > 0 else 0.0

        if label in fuzzy_engine.AREA_DEFECT_LABELS:
            physical_metric = (mask_pixels * (gsd ** 2)) / 1_000_000.0
            unit, measurement_type = "sq.m", "Area"
        else:
            physical_metric = (length_px * gsd) / 1000.0
            unit, measurement_type = "m", "Length"

        total_defect_px += mask_pixels

        pure_skeleton[y1:y2, x1:x2] = cv2.bitwise_or(pure_skeleton[y1:y2, x1:x2], skel)
        debug_img[y1:y2, x1:x2][skel > 0] = [0, 0, 255]
        cv2.rectangle(debug_img, (x1, y1), (x2, y2), (0, 255, 0), 2)

        measured.append({
            "label": label,
            "measurement_type": measurement_type,
            "metric_value": physical_metric,
            "unit": unit,
            "width_mm": width_mm,
            "mask_pixels": mask_pixels,
            "confidence": float(confidences[i]),
            "box": (int(x1), int(y1)),
        })

    if not measured:
        return empty

    # ---- Crack density over the analysed road surface ----------------------
    density_pct = (total_defect_px / road_area_px * 100.0) if road_area_px > 0 else 0.0
    density_pct = float(min(density_pct, 100.0))

    # ---- Pass 2: symbolic reasoning ----------------------------------------
    traced = []
    for m in measured:
        grades = fuzzy_engine.evaluate(
            label=m["label"],
            width_mm=m["width_mm"],
            density_pct=density_pct,
            confidence=m["confidence"],
        )

        x1, y1 = m.pop("box")
        m.pop("mask_pixels")

        entry = {**m, **grades, "crack_density_pct": round(density_pct, 2)}
        # "severity" stays the headline field the UI already reads; it now carries
        # the fuzzy grade, with the two baselines alongside it for RQ3.
        entry["severity"] = grades["severity_fuzzy"]
        traced.append(entry)

        cv2.putText(
            debug_img, f"{m['label']} ({entry['severity']})",
            (x1, max(15, y1 - 5)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2,
        )

    return traced, debug_img, pure_skeleton, density_pct


def _summary_prose(context: str) -> str:
    """Ask the local model for the narrative paragraph only."""
    prompt = f"""You are a civil engineer writing the opening paragraph of a DPWH
road maintenance bulletin.

Measured findings:
{context}

Write two or three sentences describing the condition of this road segment.
Cite the measured crack density figure exactly as given. Refer to distress types
only by the exact names listed. Do not recommend any action, do not assign a
priority, and do not state any measurement that is not listed above.
Plain prose only: no headings, no bullet points, no asterisks."""

    try:
        response = requests.post(
            f"{OLLAMA_HOST}/api/generate",
            json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
            timeout=180,
        )
        response.raise_for_status()
        return response.json().get("response", "").strip()
    except requests.exceptions.ConnectionError:
        return (
            f"[Local LLM unavailable: could not reach Ollama at {OLLAMA_HOST}. "
            f"Start it with 'ollama serve' and ensure '{OLLAMA_MODEL}' is pulled.]"
        )
    except Exception as e:
        return f"[Error generating summary with local model: {e}]"


def generate_maintenance_bulletin(distresses, density_pct, ipm_applied):
    """Assemble a DPWH-style maintenance bulletin.

    Only the opening narrative comes from the language model. The intervention
    list and the priority level are rendered directly from the symbolic layer,
    because they are maintenance decisions: a 3B model asked to restate them
    duplicated one line per detection, mislabelled distress types, and on an
    earlier revision emitted two priority levels at once.

    Keeping the decisions deterministic also means the bulletin is auditable --
    every recommendation traces to fuzzy_engine.INTERVENTIONS rather than to a
    sampled token sequence.
    """
    header = "Road Segment Health Summary:"

    if not distresses:
        return (
            f"{header}\n"
            "No structural distress was detected in the analysed road surface. "
            f"Measured crack density is {density_pct:.2f} percent.\n\n"
            "Recommended Interventions:\n"
            "  None required at this time.\n\n"
            "Priority Level:\n"
            "  Routine - no distress detected; continue scheduled monitoring."
        )

    worst = worst_severity(distresses)
    priority = fuzzy_engine.priority_level(worst, density_pct)

    # Worst severity per distress type, with how many of each were found.
    by_type = {}
    for d in distresses:
        label, severity = d["label"], d["severity_fuzzy"]
        entry = by_type.setdefault(label, {"severity": severity, "count": 0})
        entry["count"] += 1
        if SEVERITY_RANK.get(severity, 0) > SEVERITY_RANK.get(entry["severity"], 0):
            entry["severity"] = severity

    ordered = sorted(
        by_type.items(), key=lambda kv: -SEVERITY_RANK.get(kv[1]["severity"], 0)
    )

    context_lines = [f"Crack density: {density_pct:.2f} percent of the road surface"]
    if not ipm_applied:
        context_lines.append(
            "Perspective correction could not be applied, so measurements are approximate"
        )
    for label, info in ordered:
        plural = "detection" if info["count"] == 1 else "detections"
        context_lines.append(
            f"{label}: {info['count']} {plural}, severity {info['severity']}"
        )

    summary = _summary_prose("\n".join(context_lines))

    interventions = "\n".join(
        f"  {label} - severity {info['severity']} - "
        f"{fuzzy_engine.intervention_for(label, info['severity'])} "
        f"({info['count']} detected)"
        for label, info in ordered
    )

    worst_types = ", ".join(
        label for label, info in ordered if info["severity"] == worst
    )
    justification = (
        f"  {priority} - driven by {worst} severity {worst_types} "
        f"at {density_pct:.2f} percent crack density."
    )

    return (
        f"{header}\n{summary}\n\n"
        f"Recommended Interventions:\n{interventions}\n\n"
        f"Priority Level:\n{justification}"
    )


@app.post("/analyze-road")
async def analyze_road(request: ImageRequest):
    try:
        print("--- Request received ---")

        # 1. Decode
        img = decode_base64_img(request.image_base64)
        if img is None:
            return JSONResponse(status_code=400, content={"message": "Invalid Image Data"})

        # 2. Privacy pass before anything is detected, measured or returned.
        img = apply_privacy_blur(img)

        # 3. Road detection, and the gate that depends on it
        road_results = road_model.predict(img, conf=0.25)

        frame_px = img.shape[0] * img.shape[1]
        road_px = road_mask_area_px(road_results, img.shape)
        road_coverage = (road_px / frame_px) if frame_px else 0.0

        if road_coverage < MIN_ROAD_COVERAGE:
            # Refuse rather than return a confident-looking assessment of
            # something that is not a road.
            print(f"Rejected: road coverage {road_coverage:.1%} < {MIN_ROAD_COVERAGE:.0%}")
            return JSONResponse(
                status_code=422,
                content={
                    "error": "no_road_detected",
                    "message": (
                        "No road surface was detected in this image. Upload a photo "
                        "of a road taken from chest height, about 2 m from the "
                        "defect, with the pavement filling most of the frame."
                    ),
                    "road_coverage_pct": round(road_coverage * 100, 2),
                    "required_coverage_pct": round(MIN_ROAD_COVERAGE * 100, 2),
                },
            )

        print(f"Road detected: {road_coverage:.1%} of frame.")

        # 4. Inverse Perspective Mapping
        print("Calculating bird's eye view...")
        bev_img, ipm_applied = get_birds_eye_view(img, road_results)

        # Denominator for crack density. A successful warp maps the road
        # trapezoid onto the whole frame, so the frame IS the road surface.
        # Without it, fall back to the detected road mask area so we do not
        # divide by sky and verge.
        if ipm_applied:
            road_area_px = bev_img.shape[0] * bev_img.shape[1]
        else:
            road_area_px = road_px
            print("IPM not applied; measurements are perspective-distorted.")

        # 5. Crack detection on the BEV
        print("Running crack detection...")
        crack_results = detect_crack(crack_model, bev_img)

        # 6. SAM tracing, metrics, and symbolic reasoning
        gsd = request.gsd_mm_px or DEFAULT_GSD_MM_PX
        print("Tracing with SAM, measuring, and grading...")
        traced_data, debug_img, skel, density_pct = trace_cracks(
            bev_img, crack_results, predictor, gsd, road_area_px
        )

        # 7. Encode the annotated image
        _, buffer = cv2.imencode(".jpg", debug_img)
        image_url = "data:image/jpeg;base64," + base64.b64encode(buffer).decode("utf-8")

        # 8. Maintenance bulletin from the local model
        print("Generating bulletin locally...")
        bulletin = generate_maintenance_bulletin(traced_data, density_pct, ipm_applied)

        return {
            "fileUrl": image_url,
            "distresses": traced_data if traced_data else [
                {"label": "Clear", "severity": "Low", "confidence": 1.0}
            ],
            "gemini_bulletin": bulletin,
            "overall_severity": worst_severity(traced_data),
            "gsd_mm_px": gsd,
            "crack_density_pct": round(density_pct, 2),
            "ipm_applied": ipm_applied,
            "road_coverage_pct": round(road_coverage * 100, 2),
            "privacy_blur_applied": PRIVACY_BLUR_ENABLED,
        }

    except Exception as e:
        print(f"CRITICAL ERROR: {e}")
        return JSONResponse(status_code=500, content={"message": str(e)})
